obs:
  host: localhost
  port: 4455
  password: ''
ocr_corrections:
  character_equivalences:
    '4':
    - g
    - l
    - k
    s:
    - '5'
    o:
    - '0'
    i:
    - '1'
    - l
  slash_like_characters:
  - f
  - l
  - i
  - '}'
  - '1'
pes15:
  ocr_regions:
    p1_league_text:
    - 175
    - 415
    - 855
    - 465
    p1_team_select_text:
    - 175
    - 415
    - 855
    - 465
pes17:
  ocr_regions:
    p1_league_text:
    - 177
    - 375
    - 815
    - 460
    p1_team_select_text:
    - 177
    - 375
    - 815
    - 460
pes19:
  ocr_regions:
    p1_league_text:
    - 177
    - 375
    - 815
    - 460
    p1_team_select_text:
    - 177
    - 375
    - 815
    - 460
pes21:
  ocr_regions:
    p1_league_text:
    - 172
    - 372
    - 815
    - 460
    p1_team_select_text:
    - 172
    - 372
    - 815
    - 460
